# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', vendor]


# Site Settings
title: "Edintelligence | AI & Data Science Society"
#email: ""
description: "AI & Data Science Society of the University of Edinburgh"
baseurl: ""
url: "https://edintelligence.github.io"
#url: "http://localhost:4000"
#permalink: "/blog/:title"


# Head
metaKeywords: "deep learning, University of Edinburgh, machine learning, neural networks"
twitterAccount: "@edintelligence"

##
googleAnalyticsTrackingId: "UA-36376375-2"
googleAnalyticsSiteUrl: "auto"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/events/", text: "Events"}
 - {permalink: "/about/", text: "About Us"}
